### ISSUE TITLE
Melhorar captura de datas

### ISSUE THREAD

**Issue by ruiconti** [ruiconti/scheduler-agent#16]
Nos casos em que o usuário informa apenas a data (granularidade dia), o bot assume o horário como 00h, quando na verdade ele deveria perguntar o horário.

**Problema**:

```markdown
   - Tudo bem. Qual data e horário você está disponível?
* próxima segunda 
   - Deseja confirmar a data, 26/09, às 00h?
```

**Cenário ideal**:

```markdown
   - Tudo bem. Qual data e horário você está disponível?
* próxima segunda 
   - Certo. Qual horário?
* às 13h
   - Deseja confirmar a data, 26/09, às 13h?
```

**Sugestão**:

Uma simples verificação se o objeto `datetime` possui `hour != 0 and minute != 0` indicaria se seria necessário perguntar pela hora ou não. Atenção que se for buscada a data e a hora separadamente, elas devem ser "unidas" em um objeto novamente

**Comment by Julianepmello** [comment]
As alterações realizadas para resolver essa issue permitiram:

1. Demandar o horário caso seja informado somente o dia.
2. Não alterar o dia caso seja informado somente o horário (ainda não resolvido por completo).
3. Lidar com tempo extraído como intervalo (tal como "segunda de manhã"). 
4. Continuar a extrair a data e horário quando esses são informados juntos.

Contudo, a estratégia elaborada para a atualização somente do horário é baseada na extração do Duckling da informação ("quero mudar para 16h") como as entidades "time" e"duration". Mas, dependendo da forma como o usuário informa o horário (exemplo "às 16h"), é realizada a extração somente da entidade "time" e da mesma forma que uma data completa (exemplo "terça-feira às 14h"). Sendo assim, deve-se elaborar uma estratégia diferente para solução do problema.

**Comment by Julianepmello** [comment]
Para resolver a questão do horário, elaborou-se uma nova estratégia: verificar se a data extraída possui como dia o dia de hoje e se o usuário não disse a palavra "hoje" em sua mensagem anterior. Assim, caso o usuário informe somente o horário é possível alterar esse sem mudar o dia. Caso o usuário informe algo como "hoje 12h" ainda é possível alterar a data e o horário.
